# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-04 09:45
from __future__ import unicode_literals

import server.apps.tenants.models
from django.conf import settings
import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain name')),
                ('name', models.CharField(max_length=50, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the invitee', max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text='First Name of the invitee', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Last Name of the invitee', max_length=30, verbose_name='last name')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the invite created?', verbose_name='creation time')),
                ('first_clicked', models.DateTimeField(blank=True, help_text='When was the first time the invitee clicked on the invite?', null=True, verbose_name='first clicked')),
                ('inviter', models.ForeignKey(help_text='Who invited the person?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL, verbose_name='inviter')),
            ],
            options={
                'verbose_name': 'invite',
                'verbose_name_plural': 'invites',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team (the agency or company)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this tenant should be treated as active. ', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='When did the tenant join?', verbose_name='date joined')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', validators=[server.apps.tenants.models.validate_default_site])),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
            managers=[
                ('objects', server.apps.tenants.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Which user was created or connected from invite?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_used', to=settings.AUTH_USER_MODEL, verbose_name='connected user'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.Tenant'),
        ),
    ]
